version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_pipeline
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pipeline_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pipeline-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_pipeline
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pipeline-net

networks:
  pipeline-net:

volumes:
  postgres_data:
